package com.mathwise.common.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "exercises")
public class Exercise extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "knowledge_node_id", nullable = false)
    private KnowledgeNode knowledgeNode;

    @Column(name = "question_text", nullable = false, length = 1000)
    private String questionText;

    @Column(name = "correct_answer", nullable = false)
    private String correctAnswer;

    @Column(name = "difficulty_level", nullable = false)
    private int difficultyLevel;

    /**
     * True ⇒ this row was produced by the LLM path of the Phase 8 generator
     * (and validated by SymPy on the way in). False ⇒ either a seeded
     * exercise from DataSeeder, or generated by the deterministic-template
     * fallback. Used for analytics and for spotting LLM quality regressions.
     *
     * <p>{@code columnDefinition} sets the database-level default so that
     * existing rows (seeded before Phase 8) get {@code false} when Hibernate
     * adds this column under {@code ddl-auto=update}, instead of failing
     * the migration on the NOT NULL constraint.
     */
    @Column(name = "generated_by_ai", nullable = false,
            columnDefinition = "boolean default false")
    private boolean generatedByAi = false;

    public KnowledgeNode getKnowledgeNode() {
        return knowledgeNode;
    }

    public void setKnowledgeNode(KnowledgeNode knowledgeNode) {
        this.knowledgeNode = knowledgeNode;
    }

    public String getQuestionText() {
        return questionText;
    }

    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    public String getCorrectAnswer() {
        return correctAnswer;
    }

    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    public int getDifficultyLevel() {
        return difficultyLevel;
    }

    public void setDifficultyLevel(int difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    public boolean isGeneratedByAi() {
        return generatedByAi;
    }

    public void setGeneratedByAi(boolean generatedByAi) {
        this.generatedByAi = generatedByAi;
    }
}
